version: 2.1

jobs:
  build-and-test:
    machine: true
    steps:
      - checkout
      - run: make deps build
      - run: make check-self TEST="all"
      - run: make check-dummy TEST="all"
      - run: make check-fabric TEST="all ^accounting.UpstreamPppoeIp4UnicastTest ^accounting.DownstreamPppoeIp4UnicastTest ^accounting.PppoePuntTest"

workflows:
  main:
    jobs:
      - build-and-test
