# Copyright 2019-present Open Networking Foundation
#
# SPDX-License-Identifier: Apache-2.0
#

version: 2.1

jobs:
  build-and-test:
    machine: true
    steps:
      - checkout
      - run: make deps build
      - run: make check-self TEST="all"
      - run: make check-dummy TEST="all"
      - run: make check-fabric TEST="all ^accounting"

workflows:
  main:
    jobs:
      - build-and-test
