version: 2.1

jobs:
  build-and-test:
    machine: true
    steps:
      - checkout
      - run: make deps build
      - run: make check-self
      - run: make check-dummy

workflows:
  main:
    jobs:
      - build-and-test
